title: S/W Developer
url: "https://bcnote3314.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://bcnote3314.github.io/researcher/"
footer_text: "Jae Hyun"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "https://docs.google.com/document/d/1YrmlnkqHeiXENrZFBbbJvsStYyJo_J15aZanDMBajnQ/edit?usp=sharing"
 - name: "Blog"
   link: "https://bcnote3314.github.io"
